name: ShellCheck Lint

on:
  push:
    paths: ['**.sh']
  pull_request:
    paths: ['**.sh']

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck
      - name: Lint script
        run: shellcheck deb/usr/local/bin/lkdt
